//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DATAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DATAType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SECTION_PERSONAL_SETTINGS" type="{}SECTION_PERSONAL_SETTINGSType"/&gt;
 *         &lt;element name="SECTION_DIAGRAMM_SETTINGS" type="{}SECTION_DIAGRAMM_SETTINGSType"/&gt;
 *         &lt;element name="SECTION_DAILY_PROFILES" type="{}SECTION_DAILY_PROFILESType"/&gt;
 *         &lt;element name="SECTION_GLUCOMETERS" type="{}SECTION_GLUCOMETERSType"/&gt;
 *         &lt;element name="SECTION_PRODUCTS" type="{}SECTION_PRODUCTSType"/&gt;
 *         &lt;element name="SECTION_UNITS" type="{}SECTION_UNITSType"/&gt;
 *         &lt;element name="SECTION_FN" type="{}SECTION_FNType"/&gt;
 *         &lt;element name="SECTION_PERS_FN" type="{}SECTION_PERS_FNType"/&gt;
 *         &lt;element name="SECTION_GLIO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SECTION_RECORDS" type="{}SECTION_RECORDSType"/&gt;
 *         &lt;element name="SECTION_NOTIFY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SECTION_NOTIFY_DOC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATAType", propOrder = {
    "sectionpersonalsettings",
    "sectiondiagrammsettings",
    "sectiondailyprofiles",
    "sectionglucometers",
    "sectionproducts",
    "sectionunits",
    "sectionfn",
    "sectionpersfn",
    "sectionglio",
    "sectionrecords",
    "sectionnotify",
    "sectionnotifydoc"
})
public class DATAType {

    @XmlElement(name = "SECTION_PERSONAL_SETTINGS", required = true)
    protected SECTIONPERSONALSETTINGSType sectionpersonalsettings;
    @XmlElement(name = "SECTION_DIAGRAMM_SETTINGS", required = true)
    protected SECTIONDIAGRAMMSETTINGSType sectiondiagrammsettings;
    @XmlElement(name = "SECTION_DAILY_PROFILES", required = true)
    protected SECTIONDAILYPROFILESType sectiondailyprofiles;
    @XmlElement(name = "SECTION_GLUCOMETERS", required = true)
    protected SECTIONGLUCOMETERSType sectionglucometers;
    @XmlElement(name = "SECTION_PRODUCTS", required = true)
    protected SECTIONPRODUCTSType sectionproducts;
    @XmlElement(name = "SECTION_UNITS", required = true)
    protected SECTIONUNITSType sectionunits;
    @XmlElement(name = "SECTION_FN", required = true)
    protected SECTIONFNType sectionfn;
    @XmlElement(name = "SECTION_PERS_FN", required = true)
    protected SECTIONPERSFNType sectionpersfn;
    @XmlElement(name = "SECTION_GLIO", required = true)
    protected String sectionglio;
    @XmlElement(name = "SECTION_RECORDS", required = true)
    protected SECTIONRECORDSType sectionrecords;
    @XmlElement(name = "SECTION_NOTIFY", required = true)
    protected String sectionnotify;
    @XmlElement(name = "SECTION_NOTIFY_DOC", required = true)
    protected String sectionnotifydoc;
    @XmlAttribute(name = "date")
    protected String date;
    @XmlAttribute(name = "time")
    protected String time;
    @XmlAttribute(name = "source")
    protected String source;

    /**
     * Gets the value of the sectionpersonalsettings property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONPERSONALSETTINGSType }
     *     
     */
    public SECTIONPERSONALSETTINGSType getSECTIONPERSONALSETTINGS() {
        return sectionpersonalsettings;
    }

    /**
     * Sets the value of the sectionpersonalsettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONPERSONALSETTINGSType }
     *     
     */
    public void setSECTIONPERSONALSETTINGS(SECTIONPERSONALSETTINGSType value) {
        this.sectionpersonalsettings = value;
    }

    /**
     * Gets the value of the sectiondiagrammsettings property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONDIAGRAMMSETTINGSType }
     *     
     */
    public SECTIONDIAGRAMMSETTINGSType getSECTIONDIAGRAMMSETTINGS() {
        return sectiondiagrammsettings;
    }

    /**
     * Sets the value of the sectiondiagrammsettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONDIAGRAMMSETTINGSType }
     *     
     */
    public void setSECTIONDIAGRAMMSETTINGS(SECTIONDIAGRAMMSETTINGSType value) {
        this.sectiondiagrammsettings = value;
    }

    /**
     * Gets the value of the sectiondailyprofiles property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONDAILYPROFILESType }
     *     
     */
    public SECTIONDAILYPROFILESType getSECTIONDAILYPROFILES() {
        return sectiondailyprofiles;
    }

    /**
     * Sets the value of the sectiondailyprofiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONDAILYPROFILESType }
     *     
     */
    public void setSECTIONDAILYPROFILES(SECTIONDAILYPROFILESType value) {
        this.sectiondailyprofiles = value;
    }

    /**
     * Gets the value of the sectionglucometers property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONGLUCOMETERSType }
     *     
     */
    public SECTIONGLUCOMETERSType getSECTIONGLUCOMETERS() {
        return sectionglucometers;
    }

    /**
     * Sets the value of the sectionglucometers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONGLUCOMETERSType }
     *     
     */
    public void setSECTIONGLUCOMETERS(SECTIONGLUCOMETERSType value) {
        this.sectionglucometers = value;
    }

    /**
     * Gets the value of the sectionproducts property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONPRODUCTSType }
     *     
     */
    public SECTIONPRODUCTSType getSECTIONPRODUCTS() {
        return sectionproducts;
    }

    /**
     * Sets the value of the sectionproducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONPRODUCTSType }
     *     
     */
    public void setSECTIONPRODUCTS(SECTIONPRODUCTSType value) {
        this.sectionproducts = value;
    }

    /**
     * Gets the value of the sectionunits property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONUNITSType }
     *     
     */
    public SECTIONUNITSType getSECTIONUNITS() {
        return sectionunits;
    }

    /**
     * Sets the value of the sectionunits property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONUNITSType }
     *     
     */
    public void setSECTIONUNITS(SECTIONUNITSType value) {
        this.sectionunits = value;
    }

    /**
     * Gets the value of the sectionfn property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONFNType }
     *     
     */
    public SECTIONFNType getSECTIONFN() {
        return sectionfn;
    }

    /**
     * Sets the value of the sectionfn property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONFNType }
     *     
     */
    public void setSECTIONFN(SECTIONFNType value) {
        this.sectionfn = value;
    }

    /**
     * Gets the value of the sectionpersfn property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONPERSFNType }
     *     
     */
    public SECTIONPERSFNType getSECTIONPERSFN() {
        return sectionpersfn;
    }

    /**
     * Sets the value of the sectionpersfn property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONPERSFNType }
     *     
     */
    public void setSECTIONPERSFN(SECTIONPERSFNType value) {
        this.sectionpersfn = value;
    }

    /**
     * Gets the value of the sectionglio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECTIONGLIO() {
        return sectionglio;
    }

    /**
     * Sets the value of the sectionglio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECTIONGLIO(String value) {
        this.sectionglio = value;
    }

    /**
     * Gets the value of the sectionrecords property.
     * 
     * @return
     *     possible object is
     *     {@link SECTIONRECORDSType }
     *     
     */
    public SECTIONRECORDSType getSECTIONRECORDS() {
        return sectionrecords;
    }

    /**
     * Sets the value of the sectionrecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link SECTIONRECORDSType }
     *     
     */
    public void setSECTIONRECORDS(SECTIONRECORDSType value) {
        this.sectionrecords = value;
    }

    /**
     * Gets the value of the sectionnotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECTIONNOTIFY() {
        return sectionnotify;
    }

    /**
     * Sets the value of the sectionnotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECTIONNOTIFY(String value) {
        this.sectionnotify = value;
    }

    /**
     * Gets the value of the sectionnotifydoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECTIONNOTIFYDOC() {
        return sectionnotifydoc;
    }

    /**
     * Sets the value of the sectionnotifydoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECTIONNOTIFYDOC(String value) {
        this.sectionnotifydoc = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

}
