//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for GLUCOMETERType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GLUCOMETERType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="_id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sk1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sk2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="koef1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="koef2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="koef3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="edit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GLUCOMETERType", propOrder = {
    "value"
})
public class GLUCOMETERType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "_id")
    protected String id;
    @XmlAttribute(name = "guid")
    protected String guid;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "sk1")
    protected String sk1;
    @XmlAttribute(name = "sk2")
    protected String sk2;
    @XmlAttribute(name = "koef1")
    protected String koef1;
    @XmlAttribute(name = "koef2")
    protected String koef2;
    @XmlAttribute(name = "koef3")
    protected String koef3;
    @XmlAttribute(name = "edit")
    protected String edit;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the sk1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSk1() {
        return sk1;
    }

    /**
     * Sets the value of the sk1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSk1(String value) {
        this.sk1 = value;
    }

    /**
     * Gets the value of the sk2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSk2() {
        return sk2;
    }

    /**
     * Sets the value of the sk2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSk2(String value) {
        this.sk2 = value;
    }

    /**
     * Gets the value of the koef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKoef1() {
        return koef1;
    }

    /**
     * Sets the value of the koef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKoef1(String value) {
        this.koef1 = value;
    }

    /**
     * Gets the value of the koef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKoef2() {
        return koef2;
    }

    /**
     * Sets the value of the koef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKoef2(String value) {
        this.koef2 = value;
    }

    /**
     * Gets the value of the koef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKoef3() {
        return koef3;
    }

    /**
     * Sets the value of the koef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKoef3(String value) {
        this.koef3 = value;
    }

    /**
     * Gets the value of the edit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdit() {
        return edit;
    }

    /**
     * Sets the value of the edit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdit(String value) {
        this.edit = value;
    }

}
