//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DATA_QNAME = new QName("", "DATA");
    private final static QName _PRODUCTTypeSECTIONSUBPRODUCTS_QNAME = new QName("", "SECTION_SUBPRODUCTS");
    private final static QName _RECORDTypeSECTIONRECORDSTAB_QNAME = new QName("", "SECTION_RECORDS_TAB");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATAType }
     * 
     */
    public DATAType createDATAType() {
        return new DATAType();
    }

    /**
     * Create an instance of {@link SECTIONUNITSType }
     * 
     */
    public SECTIONUNITSType createSECTIONUNITSType() {
        return new SECTIONUNITSType();
    }

    /**
     * Create an instance of {@link UNITType }
     * 
     */
    public UNITType createUNITType() {
        return new UNITType();
    }

    /**
     * Create an instance of {@link RECORDType }
     * 
     */
    public RECORDType createRECORDType() {
        return new RECORDType();
    }

    /**
     * Create an instance of {@link SECTIONPRODUCTSType }
     * 
     */
    public SECTIONPRODUCTSType createSECTIONPRODUCTSType() {
        return new SECTIONPRODUCTSType();
    }

    /**
     * Create an instance of {@link FNType }
     * 
     */
    public FNType createFNType() {
        return new FNType();
    }

    /**
     * Create an instance of {@link SECTIONSUBPRODUCTSType }
     * 
     */
    public SECTIONSUBPRODUCTSType createSECTIONSUBPRODUCTSType() {
        return new SECTIONSUBPRODUCTSType();
    }

    /**
     * Create an instance of {@link SUBPRODUCTType }
     * 
     */
    public SUBPRODUCTType createSUBPRODUCTType() {
        return new SUBPRODUCTType();
    }

    /**
     * Create an instance of {@link SECTIONDAILYPROFILESType }
     * 
     */
    public SECTIONDAILYPROFILESType createSECTIONDAILYPROFILESType() {
        return new SECTIONDAILYPROFILESType();
    }

    /**
     * Create an instance of {@link GLUCOMETERType }
     * 
     */
    public GLUCOMETERType createGLUCOMETERType() {
        return new GLUCOMETERType();
    }

    /**
     * Create an instance of {@link SECTIONGLUCOMETERSType }
     * 
     */
    public SECTIONGLUCOMETERSType createSECTIONGLUCOMETERSType() {
        return new SECTIONGLUCOMETERSType();
    }

    /**
     * Create an instance of {@link PERSFNType }
     * 
     */
    public PERSFNType createPERSFNType() {
        return new PERSFNType();
    }

    /**
     * Create an instance of {@link PROFILEType }
     * 
     */
    public PROFILEType createPROFILEType() {
        return new PROFILEType();
    }

    /**
     * Create an instance of {@link SECTIONRECORDSTABType }
     * 
     */
    public SECTIONRECORDSTABType createSECTIONRECORDSTABType() {
        return new SECTIONRECORDSTABType();
    }

    /**
     * Create an instance of {@link PERSONALSETTINGSType }
     * 
     */
    public PERSONALSETTINGSType createPERSONALSETTINGSType() {
        return new PERSONALSETTINGSType();
    }

    /**
     * Create an instance of {@link SECTIONPERSONALSETTINGSType }
     * 
     */
    public SECTIONPERSONALSETTINGSType createSECTIONPERSONALSETTINGSType() {
        return new SECTIONPERSONALSETTINGSType();
    }

    /**
     * Create an instance of {@link DIAGRAMMSETTINGSType }
     * 
     */
    public DIAGRAMMSETTINGSType createDIAGRAMMSETTINGSType() {
        return new DIAGRAMMSETTINGSType();
    }

    /**
     * Create an instance of {@link SECTIONPERSFNType }
     * 
     */
    public SECTIONPERSFNType createSECTIONPERSFNType() {
        return new SECTIONPERSFNType();
    }

    /**
     * Create an instance of {@link SECTIONFNType }
     * 
     */
    public SECTIONFNType createSECTIONFNType() {
        return new SECTIONFNType();
    }

    /**
     * Create an instance of {@link SECTIONDIAGRAMMSETTINGSType }
     * 
     */
    public SECTIONDIAGRAMMSETTINGSType createSECTIONDIAGRAMMSETTINGSType() {
        return new SECTIONDIAGRAMMSETTINGSType();
    }

    /**
     * Create an instance of {@link SECTIONRECORDSType }
     * 
     */
    public SECTIONRECORDSType createSECTIONRECORDSType() {
        return new SECTIONRECORDSType();
    }

    /**
     * Create an instance of {@link RECORDTABType }
     * 
     */
    public RECORDTABType createRECORDTABType() {
        return new RECORDTABType();
    }

    /**
     * Create an instance of {@link PRODUCTType }
     * 
     */
    public PRODUCTType createPRODUCTType() {
        return new PRODUCTType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DATAType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATA")
    public JAXBElement<DATAType> createDATA(DATAType value) {
        return new JAXBElement<DATAType>(_DATA_QNAME, DATAType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SECTIONSUBPRODUCTSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SECTION_SUBPRODUCTS", scope = PRODUCTType.class)
    public JAXBElement<SECTIONSUBPRODUCTSType> createPRODUCTTypeSECTIONSUBPRODUCTS(SECTIONSUBPRODUCTSType value) {
        return new JAXBElement<SECTIONSUBPRODUCTSType>(_PRODUCTTypeSECTIONSUBPRODUCTS_QNAME, SECTIONSUBPRODUCTSType.class, PRODUCTType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SECTIONRECORDSTABType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SECTION_RECORDS_TAB", scope = RECORDType.class)
    public JAXBElement<SECTIONRECORDSTABType> createRECORDTypeSECTIONRECORDSTAB(SECTIONRECORDSTABType value) {
        return new JAXBElement<SECTIONRECORDSTABType>(_RECORDTypeSECTIONRECORDSTAB_QNAME, SECTIONRECORDSTABType.class, RECORDType.class, value);
    }

}
