//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRODUCTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRODUCTType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SECTION_SUBPRODUCTS" type="{}SECTION_SUBPRODUCTSType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="_id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="zh" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="u" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="b2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="zh2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="u2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="gi" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="kkal" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="gr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="codeparent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guidparent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="composite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="complex" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="favorite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guidunit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="portion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="edit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRODUCTType", propOrder = {
    "content"
})
public class PRODUCTType {

    @XmlElementRef(name = "SECTION_SUBPRODUCTS", type = JAXBElement.class, required = false)
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "_id")
    protected String id;
    @XmlAttribute(name = "guid")
    protected String guid;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "b")
    protected String b;
    @XmlAttribute(name = "zh")
    protected String zh;
    @XmlAttribute(name = "u")
    protected String u;
    @XmlAttribute(name = "b2")
    protected String b2;
    @XmlAttribute(name = "zh2")
    protected String zh2;
    @XmlAttribute(name = "u2")
    protected String u2;
    @XmlAttribute(name = "gi")
    protected String gi;
    @XmlAttribute(name = "kkal")
    protected String kkal;
    @XmlAttribute(name = "gr")
    protected String gr;
    @XmlAttribute(name = "codeparent")
    protected String codeparent;
    @XmlAttribute(name = "guidparent")
    protected String guidparent;
    @XmlAttribute(name = "composite")
    protected String composite;
    @XmlAttribute(name = "complex")
    protected String complex;
    @XmlAttribute(name = "favorite")
    protected String favorite;
    @XmlAttribute(name = "unit")
    protected String unit;
    @XmlAttribute(name = "guidunit")
    protected String guidunit;
    @XmlAttribute(name = "count")
    protected String count;
    @XmlAttribute(name = "portion")
    protected String portion;
    @XmlAttribute(name = "edit")
    protected String edit;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link SECTIONSUBPRODUCTSType }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the b property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setB(String value) {
        this.b = value;
    }

    /**
     * Gets the value of the zh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZh() {
        return zh;
    }

    /**
     * Sets the value of the zh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZh(String value) {
        this.zh = value;
    }

    /**
     * Gets the value of the u property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getU() {
        return u;
    }

    /**
     * Sets the value of the u property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setU(String value) {
        this.u = value;
    }

    /**
     * Gets the value of the b2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getB2() {
        return b2;
    }

    /**
     * Sets the value of the b2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setB2(String value) {
        this.b2 = value;
    }

    /**
     * Gets the value of the zh2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZh2() {
        return zh2;
    }

    /**
     * Sets the value of the zh2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZh2(String value) {
        this.zh2 = value;
    }

    /**
     * Gets the value of the u2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getU2() {
        return u2;
    }

    /**
     * Sets the value of the u2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setU2(String value) {
        this.u2 = value;
    }

    /**
     * Gets the value of the gi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGi() {
        return gi;
    }

    /**
     * Sets the value of the gi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGi(String value) {
        this.gi = value;
    }

    /**
     * Gets the value of the kkal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKkal() {
        return kkal;
    }

    /**
     * Sets the value of the kkal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKkal(String value) {
        this.kkal = value;
    }

    /**
     * Gets the value of the gr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGr() {
        return gr;
    }

    /**
     * Sets the value of the gr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGr(String value) {
        this.gr = value;
    }

    /**
     * Gets the value of the codeparent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeparent() {
        return codeparent;
    }

    /**
     * Sets the value of the codeparent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeparent(String value) {
        this.codeparent = value;
    }

    /**
     * Gets the value of the guidparent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidparent() {
        return guidparent;
    }

    /**
     * Sets the value of the guidparent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidparent(String value) {
        this.guidparent = value;
    }

    /**
     * Gets the value of the composite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComposite() {
        return composite;
    }

    /**
     * Sets the value of the composite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComposite(String value) {
        this.composite = value;
    }

    /**
     * Gets the value of the complex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplex() {
        return complex;
    }

    /**
     * Sets the value of the complex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplex(String value) {
        this.complex = value;
    }

    /**
     * Gets the value of the favorite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavorite() {
        return favorite;
    }

    /**
     * Sets the value of the favorite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavorite(String value) {
        this.favorite = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the guidunit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidunit() {
        return guidunit;
    }

    /**
     * Sets the value of the guidunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidunit(String value) {
        this.guidunit = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the portion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortion() {
        return portion;
    }

    /**
     * Sets the value of the portion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortion(String value) {
        this.portion = value;
    }

    /**
     * Gets the value of the edit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdit() {
        return edit;
    }

    /**
     * Sets the value of the edit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdit(String value) {
        this.edit = value;
    }

}
