//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for PROFILEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROFILEType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="_id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time0" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time10" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time11" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k10" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k11" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k12" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k13" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k14" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k15" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cei0" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cei1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cei2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cei3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cei4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cei5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="typek2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="di0" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="di1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="edit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROFILEType", propOrder = {
    "value"
})
public class PROFILEType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "_id")
    protected String id;
    @XmlAttribute(name = "guid")
    protected String guid;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "time0")
    protected String time0;
    @XmlAttribute(name = "time1")
    protected String time1;
    @XmlAttribute(name = "time2")
    protected String time2;
    @XmlAttribute(name = "time3")
    protected String time3;
    @XmlAttribute(name = "time4")
    protected String time4;
    @XmlAttribute(name = "time5")
    protected String time5;
    @XmlAttribute(name = "time10")
    protected String time10;
    @XmlAttribute(name = "time11")
    protected String time11;
    @XmlAttribute(name = "k10")
    protected String k10;
    @XmlAttribute(name = "k11")
    protected String k11;
    @XmlAttribute(name = "k12")
    protected String k12;
    @XmlAttribute(name = "k13")
    protected String k13;
    @XmlAttribute(name = "k14")
    protected String k14;
    @XmlAttribute(name = "k15")
    protected String k15;
    @XmlAttribute(name = "cei0")
    protected String cei0;
    @XmlAttribute(name = "cei1")
    protected String cei1;
    @XmlAttribute(name = "cei2")
    protected String cei2;
    @XmlAttribute(name = "cei3")
    protected String cei3;
    @XmlAttribute(name = "cei4")
    protected String cei4;
    @XmlAttribute(name = "cei5")
    protected String cei5;
    @XmlAttribute(name = "schema")
    protected String schema;
    @XmlAttribute(name = "typek2")
    protected String typek2;
    @XmlAttribute(name = "k2")
    protected String k2;
    @XmlAttribute(name = "di0")
    protected String di0;
    @XmlAttribute(name = "di1")
    protected String di1;
    @XmlAttribute(name = "edit")
    protected String edit;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the time0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime0() {
        return time0;
    }

    /**
     * Sets the value of the time0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime0(String value) {
        this.time0 = value;
    }

    /**
     * Gets the value of the time1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime1() {
        return time1;
    }

    /**
     * Sets the value of the time1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime1(String value) {
        this.time1 = value;
    }

    /**
     * Gets the value of the time2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime2() {
        return time2;
    }

    /**
     * Sets the value of the time2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime2(String value) {
        this.time2 = value;
    }

    /**
     * Gets the value of the time3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime3() {
        return time3;
    }

    /**
     * Sets the value of the time3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime3(String value) {
        this.time3 = value;
    }

    /**
     * Gets the value of the time4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime4() {
        return time4;
    }

    /**
     * Sets the value of the time4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime4(String value) {
        this.time4 = value;
    }

    /**
     * Gets the value of the time5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime5() {
        return time5;
    }

    /**
     * Sets the value of the time5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime5(String value) {
        this.time5 = value;
    }

    /**
     * Gets the value of the time10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime10() {
        return time10;
    }

    /**
     * Sets the value of the time10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime10(String value) {
        this.time10 = value;
    }

    /**
     * Gets the value of the time11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime11() {
        return time11;
    }

    /**
     * Sets the value of the time11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime11(String value) {
        this.time11 = value;
    }

    /**
     * Gets the value of the k10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK10() {
        return k10;
    }

    /**
     * Sets the value of the k10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK10(String value) {
        this.k10 = value;
    }

    /**
     * Gets the value of the k11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK11() {
        return k11;
    }

    /**
     * Sets the value of the k11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK11(String value) {
        this.k11 = value;
    }

    /**
     * Gets the value of the k12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK12() {
        return k12;
    }

    /**
     * Sets the value of the k12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK12(String value) {
        this.k12 = value;
    }

    /**
     * Gets the value of the k13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK13() {
        return k13;
    }

    /**
     * Sets the value of the k13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK13(String value) {
        this.k13 = value;
    }

    /**
     * Gets the value of the k14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK14() {
        return k14;
    }

    /**
     * Sets the value of the k14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK14(String value) {
        this.k14 = value;
    }

    /**
     * Gets the value of the k15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK15() {
        return k15;
    }

    /**
     * Sets the value of the k15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK15(String value) {
        this.k15 = value;
    }

    /**
     * Gets the value of the cei0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei0() {
        return cei0;
    }

    /**
     * Sets the value of the cei0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei0(String value) {
        this.cei0 = value;
    }

    /**
     * Gets the value of the cei1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei1() {
        return cei1;
    }

    /**
     * Sets the value of the cei1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei1(String value) {
        this.cei1 = value;
    }

    /**
     * Gets the value of the cei2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei2() {
        return cei2;
    }

    /**
     * Sets the value of the cei2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei2(String value) {
        this.cei2 = value;
    }

    /**
     * Gets the value of the cei3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei3() {
        return cei3;
    }

    /**
     * Sets the value of the cei3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei3(String value) {
        this.cei3 = value;
    }

    /**
     * Gets the value of the cei4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei4() {
        return cei4;
    }

    /**
     * Sets the value of the cei4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei4(String value) {
        this.cei4 = value;
    }

    /**
     * Gets the value of the cei5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei5() {
        return cei5;
    }

    /**
     * Sets the value of the cei5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei5(String value) {
        this.cei5 = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the typek2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypek2() {
        return typek2;
    }

    /**
     * Sets the value of the typek2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypek2(String value) {
        this.typek2 = value;
    }

    /**
     * Gets the value of the k2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK2() {
        return k2;
    }

    /**
     * Sets the value of the k2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK2(String value) {
        this.k2 = value;
    }

    /**
     * Gets the value of the di0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDi0() {
        return di0;
    }

    /**
     * Sets the value of the di0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDi0(String value) {
        this.di0 = value;
    }

    /**
     * Gets the value of the di1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDi1() {
        return di1;
    }

    /**
     * Sets the value of the di1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDi1(String value) {
        this.di1 = value;
    }

    /**
     * Gets the value of the edit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdit() {
        return edit;
    }

    /**
     * Sets the value of the edit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdit(String value) {
        this.edit = value;
    }

}
