//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RECORDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RECORDType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SECTION_RECORDS_TAB" type="{}SECTION_RECORDS_TABType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="_id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="glu_guid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="glu_koef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="glu_manual" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sk1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sk2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="he" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bzhe" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="gi" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="kkal" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="di" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="is_calculated" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cei" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="k2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="csk" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki_ras1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki_ras2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki_ras3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki_ras4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki_ras5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki_ras6" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ki_ras7" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guidfn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="minfn" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="coment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sort" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="divide" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isnotify" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="timenotify" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="textnotify" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="vibro" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="soundrepeat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="countrepeat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guid_profile" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="place_figners" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="place_stomach" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="place_feet" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="place_coment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RECORDType", propOrder = {
    "content"
})
public class RECORDType {

    @XmlElementRef(name = "SECTION_RECORDS_TAB", type = JAXBElement.class, required = false)
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "_id")
    protected String id;
    @XmlAttribute(name = "date")
    protected String date;
    @XmlAttribute(name = "time")
    protected String time;
    @XmlAttribute(name = "glu_guid")
    protected String gluGuid;
    @XmlAttribute(name = "glu_koef")
    protected String gluKoef;
    @XmlAttribute(name = "glu_manual")
    protected String gluManual;
    @XmlAttribute(name = "sk1")
    protected String sk1;
    @XmlAttribute(name = "sk2")
    protected String sk2;
    @XmlAttribute(name = "he")
    protected String he;
    @XmlAttribute(name = "bzhe")
    protected String bzhe;
    @XmlAttribute(name = "gi")
    protected String gi;
    @XmlAttribute(name = "kkal")
    protected String kkal;
    @XmlAttribute(name = "ki")
    protected String ki;
    @XmlAttribute(name = "ki1")
    protected String ki1;
    @XmlAttribute(name = "ki2")
    protected String ki2;
    @XmlAttribute(name = "di")
    protected String di;
    @XmlAttribute(name = "is_calculated")
    protected String isCalculated;
    @XmlAttribute(name = "k1")
    protected String k1;
    @XmlAttribute(name = "cei")
    protected String cei;
    @XmlAttribute(name = "k2")
    protected String k2;
    @XmlAttribute(name = "csk")
    protected String csk;
    @XmlAttribute(name = "ki_ras1")
    protected String kiRas1;
    @XmlAttribute(name = "ki_ras2")
    protected String kiRas2;
    @XmlAttribute(name = "ki_ras3")
    protected String kiRas3;
    @XmlAttribute(name = "ki_ras4")
    protected String kiRas4;
    @XmlAttribute(name = "ki_ras5")
    protected String kiRas5;
    @XmlAttribute(name = "ki_ras6")
    protected String kiRas6;
    @XmlAttribute(name = "ki_ras7")
    protected String kiRas7;
    @XmlAttribute(name = "fn")
    protected String fn;
    @XmlAttribute(name = "guidfn")
    protected String guidfn;
    @XmlAttribute(name = "minfn")
    protected String minfn;
    @XmlAttribute(name = "coment")
    protected String coment;
    @XmlAttribute(name = "sort")
    protected String sort;
    @XmlAttribute(name = "divide")
    protected String divide;
    @XmlAttribute(name = "isnotify")
    protected String isnotify;
    @XmlAttribute(name = "timenotify")
    protected String timenotify;
    @XmlAttribute(name = "textnotify")
    protected String textnotify;
    @XmlAttribute(name = "vibro")
    protected String vibro;
    @XmlAttribute(name = "soundrepeat")
    protected String soundrepeat;
    @XmlAttribute(name = "countrepeat")
    protected String countrepeat;
    @XmlAttribute(name = "guid_profile")
    protected String guidProfile;
    @XmlAttribute(name = "place_figners")
    protected String placeFigners;
    @XmlAttribute(name = "place_stomach")
    protected String placeStomach;
    @XmlAttribute(name = "place_feet")
    protected String placeFeet;
    @XmlAttribute(name = "place_coment")
    protected String placeComent;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SECTIONRECORDSTABType }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the gluGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGluGuid() {
        return gluGuid;
    }

    /**
     * Sets the value of the gluGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGluGuid(String value) {
        this.gluGuid = value;
    }

    /**
     * Gets the value of the gluKoef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGluKoef() {
        return gluKoef;
    }

    /**
     * Sets the value of the gluKoef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGluKoef(String value) {
        this.gluKoef = value;
    }

    /**
     * Gets the value of the gluManual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGluManual() {
        return gluManual;
    }

    /**
     * Sets the value of the gluManual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGluManual(String value) {
        this.gluManual = value;
    }

    /**
     * Gets the value of the sk1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSk1() {
        return sk1;
    }

    /**
     * Sets the value of the sk1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSk1(String value) {
        this.sk1 = value;
    }

    /**
     * Gets the value of the sk2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSk2() {
        return sk2;
    }

    /**
     * Sets the value of the sk2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSk2(String value) {
        this.sk2 = value;
    }

    /**
     * Gets the value of the he property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHe() {
        return he;
    }

    /**
     * Sets the value of the he property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHe(String value) {
        this.he = value;
    }

    /**
     * Gets the value of the bzhe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBzhe() {
        return bzhe;
    }

    /**
     * Sets the value of the bzhe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBzhe(String value) {
        this.bzhe = value;
    }

    /**
     * Gets the value of the gi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGi() {
        return gi;
    }

    /**
     * Sets the value of the gi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGi(String value) {
        this.gi = value;
    }

    /**
     * Gets the value of the kkal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKkal() {
        return kkal;
    }

    /**
     * Sets the value of the kkal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKkal(String value) {
        this.kkal = value;
    }

    /**
     * Gets the value of the ki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKi() {
        return ki;
    }

    /**
     * Sets the value of the ki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKi(String value) {
        this.ki = value;
    }

    /**
     * Gets the value of the ki1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKi1() {
        return ki1;
    }

    /**
     * Sets the value of the ki1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKi1(String value) {
        this.ki1 = value;
    }

    /**
     * Gets the value of the ki2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKi2() {
        return ki2;
    }

    /**
     * Sets the value of the ki2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKi2(String value) {
        this.ki2 = value;
    }

    /**
     * Gets the value of the di property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDi() {
        return di;
    }

    /**
     * Sets the value of the di property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDi(String value) {
        this.di = value;
    }

    /**
     * Gets the value of the isCalculated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCalculated() {
        return isCalculated;
    }

    /**
     * Sets the value of the isCalculated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCalculated(String value) {
        this.isCalculated = value;
    }

    /**
     * Gets the value of the k1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK1() {
        return k1;
    }

    /**
     * Sets the value of the k1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK1(String value) {
        this.k1 = value;
    }

    /**
     * Gets the value of the cei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCei() {
        return cei;
    }

    /**
     * Sets the value of the cei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCei(String value) {
        this.cei = value;
    }

    /**
     * Gets the value of the k2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK2() {
        return k2;
    }

    /**
     * Sets the value of the k2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK2(String value) {
        this.k2 = value;
    }

    /**
     * Gets the value of the csk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsk() {
        return csk;
    }

    /**
     * Sets the value of the csk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsk(String value) {
        this.csk = value;
    }

    /**
     * Gets the value of the kiRas1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKiRas1() {
        return kiRas1;
    }

    /**
     * Sets the value of the kiRas1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKiRas1(String value) {
        this.kiRas1 = value;
    }

    /**
     * Gets the value of the kiRas2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKiRas2() {
        return kiRas2;
    }

    /**
     * Sets the value of the kiRas2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKiRas2(String value) {
        this.kiRas2 = value;
    }

    /**
     * Gets the value of the kiRas3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKiRas3() {
        return kiRas3;
    }

    /**
     * Sets the value of the kiRas3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKiRas3(String value) {
        this.kiRas3 = value;
    }

    /**
     * Gets the value of the kiRas4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKiRas4() {
        return kiRas4;
    }

    /**
     * Sets the value of the kiRas4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKiRas4(String value) {
        this.kiRas4 = value;
    }

    /**
     * Gets the value of the kiRas5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKiRas5() {
        return kiRas5;
    }

    /**
     * Sets the value of the kiRas5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKiRas5(String value) {
        this.kiRas5 = value;
    }

    /**
     * Gets the value of the kiRas6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKiRas6() {
        return kiRas6;
    }

    /**
     * Sets the value of the kiRas6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKiRas6(String value) {
        this.kiRas6 = value;
    }

    /**
     * Gets the value of the kiRas7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKiRas7() {
        return kiRas7;
    }

    /**
     * Sets the value of the kiRas7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKiRas7(String value) {
        this.kiRas7 = value;
    }

    /**
     * Gets the value of the fn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFn() {
        return fn;
    }

    /**
     * Sets the value of the fn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFn(String value) {
        this.fn = value;
    }

    /**
     * Gets the value of the guidfn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidfn() {
        return guidfn;
    }

    /**
     * Sets the value of the guidfn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidfn(String value) {
        this.guidfn = value;
    }

    /**
     * Gets the value of the minfn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinfn() {
        return minfn;
    }

    /**
     * Sets the value of the minfn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinfn(String value) {
        this.minfn = value;
    }

    /**
     * Gets the value of the coment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComent() {
        return coment;
    }

    /**
     * Sets the value of the coment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComent(String value) {
        this.coment = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSort(String value) {
        this.sort = value;
    }

    /**
     * Gets the value of the divide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivide() {
        return divide;
    }

    /**
     * Sets the value of the divide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivide(String value) {
        this.divide = value;
    }

    /**
     * Gets the value of the isnotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsnotify() {
        return isnotify;
    }

    /**
     * Sets the value of the isnotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsnotify(String value) {
        this.isnotify = value;
    }

    /**
     * Gets the value of the timenotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimenotify() {
        return timenotify;
    }

    /**
     * Sets the value of the timenotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimenotify(String value) {
        this.timenotify = value;
    }

    /**
     * Gets the value of the textnotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextnotify() {
        return textnotify;
    }

    /**
     * Sets the value of the textnotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextnotify(String value) {
        this.textnotify = value;
    }

    /**
     * Gets the value of the vibro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVibro() {
        return vibro;
    }

    /**
     * Sets the value of the vibro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVibro(String value) {
        this.vibro = value;
    }

    /**
     * Gets the value of the soundrepeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoundrepeat() {
        return soundrepeat;
    }

    /**
     * Sets the value of the soundrepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoundrepeat(String value) {
        this.soundrepeat = value;
    }

    /**
     * Gets the value of the countrepeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountrepeat() {
        return countrepeat;
    }

    /**
     * Sets the value of the countrepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountrepeat(String value) {
        this.countrepeat = value;
    }

    /**
     * Gets the value of the guidProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidProfile() {
        return guidProfile;
    }

    /**
     * Sets the value of the guidProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidProfile(String value) {
        this.guidProfile = value;
    }

    /**
     * Gets the value of the placeFigners property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceFigners() {
        return placeFigners;
    }

    /**
     * Sets the value of the placeFigners property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceFigners(String value) {
        this.placeFigners = value;
    }

    /**
     * Gets the value of the placeStomach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceStomach() {
        return placeStomach;
    }

    /**
     * Sets the value of the placeStomach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceStomach(String value) {
        this.placeStomach = value;
    }

    /**
     * Gets the value of the placeFeet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceFeet() {
        return placeFeet;
    }

    /**
     * Sets the value of the placeFeet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceFeet(String value) {
        this.placeFeet = value;
    }

    /**
     * Gets the value of the placeComent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceComent() {
        return placeComent;
    }

    /**
     * Sets the value of the placeComent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceComent(String value) {
        this.placeComent = value;
    }


}
