//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for RECORD_TABType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RECORD_TABType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="_id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="idrec" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="product" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="guidproduct" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="kol" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="he" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bzhe" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="zh" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="u" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="gi" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="kkal" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sort" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RECORD_TABType", propOrder = {
    "value"
})
public class RECORDTABType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "_id")
    protected String id;
    @XmlAttribute(name = "idrec")
    protected String idrec;
    @XmlAttribute(name = "date")
    protected String date;
    @XmlAttribute(name = "product")
    protected String product;
    @XmlAttribute(name = "guidproduct")
    protected String guidproduct;
    @XmlAttribute(name = "kol")
    protected String kol;
    @XmlAttribute(name = "he")
    protected String he;
    @XmlAttribute(name = "bzhe")
    protected String bzhe;
    @XmlAttribute(name = "b")
    protected String b;
    @XmlAttribute(name = "zh")
    protected String zh;
    @XmlAttribute(name = "u")
    protected String u;
    @XmlAttribute(name = "gi")
    protected String gi;
    @XmlAttribute(name = "kkal")
    protected String kkal;
    @XmlAttribute(name = "sort")
    protected String sort;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idrec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdrec() {
        return idrec;
    }

    /**
     * Sets the value of the idrec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdrec(String value) {
        this.idrec = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the guidproduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuidproduct() {
        return guidproduct;
    }

    /**
     * Sets the value of the guidproduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuidproduct(String value) {
        this.guidproduct = value;
    }

    /**
     * Gets the value of the kol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKol() {
        return kol;
    }

    /**
     * Sets the value of the kol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKol(String value) {
        this.kol = value;
    }

    /**
     * Gets the value of the he property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHe() {
        return he;
    }

    /**
     * Sets the value of the he property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHe(String value) {
        this.he = value;
    }

    /**
     * Gets the value of the bzhe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBzhe() {
        return bzhe;
    }

    /**
     * Sets the value of the bzhe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBzhe(String value) {
        this.bzhe = value;
    }

    /**
     * Gets the value of the b property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setB(String value) {
        this.b = value;
    }

    /**
     * Gets the value of the zh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZh() {
        return zh;
    }

    /**
     * Sets the value of the zh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZh(String value) {
        this.zh = value;
    }

    /**
     * Gets the value of the u property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getU() {
        return u;
    }

    /**
     * Sets the value of the u property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setU(String value) {
        this.u = value;
    }

    /**
     * Gets the value of the gi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGi() {
        return gi;
    }

    /**
     * Sets the value of the gi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGi(String value) {
        this.gi = value;
    }

    /**
     * Gets the value of the kkal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKkal() {
        return kkal;
    }

    /**
     * Sets the value of the kkal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKkal(String value) {
        this.kkal = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSort(String value) {
        this.sort = value;
    }

}
