//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:27:18 PM EET 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SECTION_DIAGRAMM_SETTINGSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SECTION_DIAGRAMM_SETTINGSType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DIAGRAMM_SETTINGS" type="{}DIAGRAMM_SETTINGSType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SECTION_DIAGRAMM_SETTINGSType", propOrder = {
    "diagrammsettings"
})
public class SECTIONDIAGRAMMSETTINGSType {

    @XmlElement(name = "DIAGRAMM_SETTINGS")
    protected List<DIAGRAMMSETTINGSType> diagrammsettings;

    /**
     * Gets the value of the diagrammsettings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagrammsettings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDIAGRAMMSETTINGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DIAGRAMMSETTINGSType }
     * 
     * 
     */
    public List<DIAGRAMMSETTINGSType> getDIAGRAMMSETTINGS() {
        if (diagrammsettings == null) {
            diagrammsettings = new ArrayList<DIAGRAMMSETTINGSType>();
        }
        return this.diagrammsettings;
    }

}
